name: NodeJS Gulp Build DevBranch and AutoPreRelease

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp chrome
        
    - name: Zip the build
      run: zip dev-build.zip ./build/chrome/* -r
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "devbuild"
        prerelease: true
        files: |
          dev-build.zip
      id: "dev_releases"
